// examples/basic-vue/src/App.vue
<template>
  <div class="root">
    <div class="touchpoint-list" :key="this.currentData" v-if="currentData != []">
      <p>aktuelle Touchpoints</p>
      <ul>
        <li v-for="data in this.currentData.points">{{data}}</li>
      </ul>
    </div>
    <Home></Home>
  </div>
</template>

<script>
import Home from './views/Home.vue';


export default {
    name: "App",
    data() {
        return {
            connection: null,
            currentData: {
                points: [],
                webSocketAddress: "ws://",
                frameNumber: 0,
                isConnected: false
            }
        };
    },
    methods: {
        sendMessage: function (message) {
            this.connection.send(message);
        },
        updateData(points, address, frameNumber, isConnected) {
          const width = window.innerWidth;
          const height = window.innerHeight;          

          const convertedPoints = points.map((p) => {
            return {
              id: p.TouchId,
              posX: p.Position.X * width,
              posY: p.Position.Y * height,
              posZ: p.Position.Z
            }
          })

          this.currentData = {
              points: convertedPoints,
              webSocketAddress: address,
              frameNumber: frameNumber,
              isConnected: isConnected
          };
        }
    },
    provide() {
        const touchData = {};
        Object.defineProperty(touchData, "points", {
            enumerable: true,
            get: () => this.currentData.points,
        });
        Object.defineProperty(touchData, "webSocketAddress", {
          get: () => this.currentData.webSocketAddress
        });
        Object.defineProperty(touchData, "frameNumber", {
          get: () => this.currentData.frameNumber
        });
        Object.defineProperty(touchData, "isConnected", {
          get: () => this.currentData.isConnected
        });
        return {
            touchData
        };
    },
    created: function () {
        const address = "ws://localhost:40001/ReFlex";
        var frameNumber = 0;
        const that = this;
        console.log("Starting connection to WebSocket Server");
        this.connection = new WebSocket("ws://localhost:40001/ReFlex");
        this.connection.onmessage = function (event) {
            if (event.data != []) {
                //console.log("new message detected");
                //console.log(event.data);
                var points = JSON.parse(event.data);
                if (points.length < 0) {
                    return;
                }
                frameNumber++;
                that.updateData(points, address, frameNumber, true);
            }
        };
        this.connection.onopen = function (event) {
            console.log(event);
            console.log("Successfully connected to the echo websocket server...");
            that.updateData([], address, frameNumber, true);
        };
        this.connection.onclose = function (event) {
            console.log(event);
            console.log("Connection closed.");
            that.updateData([], address, frameNumber, false);
        };
    },
    components: { Home }
};
</script>

// examples/basic-react/src/app.tsx
import { Component, ReactNode } from 'react';
import { AppProps } from './types/app-props';
import { TouchPoint } from './components/TouchPoint';
import { TouchPointState } from './types/touch-point-state';
import { Interaction } from '@reflex/shared-types';
import { Status } from './components/Status';
import { History } from './components/History';

export class ReFlexApp extends Component<AppProps, TouchPointState> {
  private readonly ws: WebSocket;

  constructor(props: AppProps) {
    super(props);
    this.state = {
      points: [],
      frameNumber: 0,
      webSocketAddress: props.wsAddress,
      isConnected: false,
    };

    this.ws = new WebSocket(props.wsAddress);
  }

  componentDidMount(): void {
    this.update = this.update.bind(this);

    this.ws.onopen = () => {
      console.log("Successfully connected to " + this.props.wsAddress);

      this.update([], true);
    };

    this.ws.onmessage = (evt) => {
      // convert json from PascalCase to camelCase
      const convertToLowerCase = evt.data.replace(
        /"([^"]+)":/g,
        (_$0: string, $1: string) => {
          return '"' + $1.charAt(0).toLowerCase() + $1.slice(1) + '":';
        }
      );

      // parse data
      const points: Interaction[] = JSON.parse(
        convertToLowerCase
      ) as Interaction[];

      if (!points || points.length < 0) {
        return;
      }

      points.forEach((p) => {
        p.position.x = p.position.x * this.props.width;
        p.position.y = p.position.y * this.props.height;
      });

      this.update(points, true);
    };

    this.ws.onclose = () => {
      // websocket is closed.
      console.warn("Connection is closed...");

      this.update([], false);
    };
  }

  render(): ReactNode {
    return (
      <div>
        <div className="status__panel">
          <Status
            webSocketAddress={this.state.webSocketAddress}
            points={this.state.points}
            isConnected={this.state.isConnected}
            frameNumber={this.state.frameNumber}
          />
        </div>
        <div className="touchpoints__panel">
          {this.state.points.map((p) => (
            <TouchPoint
              key={p.touchId}
              touchId={p.touchId}
              position={p.position}
              confidence={p.confidence}
              type={p.type}
              time={p.time}
              extremumDescription={p.extremumDescription}
            />
          ))}
        </div>
        <div className="message-container">
            <History
              frameId={this.state.frameNumber}
              interactions={this.state.points}
            />
      </div>
      </div>
    );
  }

  private update(points: Interaction[], isConnected: boolean): void {
    this.setState({
      points: points,
      frameNumber: this.state.frameNumber + 1,
      isConnected: isConnected,
      webSocketAddress: this.state.webSocketAddress,
    });
  }
}
