// examples/basic-vue/src/components/TouchPoint.vue
<template>
  <div>
    <div
      className="touchPoint"
      :style="{ transform: 'translate(' + point.posX + 'px, ' + point.posY + 'px) scale(' + scaleValue + ', ' + scaleValue + ')' }"
    >
    <div :class="className"></div>
      <div class="touchPoint__innerCircle">
        <p>
          {{ point.id }}
        </p>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: "TouchPoint",

  props: {
    point:  
      {
          id: Number,
          posX: Number,
          posY: Number,
          posZ: Number,
          
        }
  },

  computed: {    
    scaleValue() {
      if (this.point.posZ) {
        return Math.abs(this.point.posZ);
      } else {
        return 0;
      }
    },

    className() {
      if (this.point.posZ) {
        return `touchPoint__outerCircle ${this.point.posZ < 0 ? ' push' : ' pull'}`;
      } else {
        return "touchPoint__outerCircle";
      }
    }
  },

  methods: {},
};
</script>

// examples/basic-react/src/components/TouchPoint.tsx
import { Component } from 'react'
import { Interaction } from '@reflex/shared-types';

// component for rendering point
export class TouchPoint extends Component<Interaction> {
  render() {
    return (
        <div key={this.props.touchId} className='touchPoint' style = {
            {
              transform: `translate(${this.props.position.x}px, ${this.props.position.y}px) scale(${Math.abs(this.props.position.z)}, ${Math.abs(this.props.position.z)})`
            }
          } >
          <div className={`touchPoint__outerCircle ${this.props.position.z < 0 ? ' push' : ' pull'}`}></div>
          <div className='touchPoint__innerCircle'>
            <p>{this.props.touchId}</p>
          </div>

        </div>
    )
  }
}
