// examples/basic-react/src/components/Status.tsx
import { Component } from 'react'
import { TouchPointState } from '../types/touch-point-state';

// component for rendering point
export class Status extends Component<TouchPointState> {
  constructor(props: TouchPointState) {
      super(props);
  }

  render() {
    return (
        <div className="status__stats">
        <div className="status__stats--header">
            <div className={`status__indicator ${this.props.isConnected ? ' connected' : ' disconnected'}`}></div>
            <p>Address</p>
        </div>
        <div className="status__stats--item">{this.props.webSocketAddress}</div>
        <div className="status__stats--header">FrameNumber</div>
        <div className="status__stats--item">{this.props.frameNumber}</div>
        <div className="status__stats--header">Touches</div>
        <div className="status__stats--item">{this.props.points.length}</div>
      </div>
    )
  }
}

// examples/basic-vue/src/components/Status.vue
<template>
  <div class="status__stats">
    <div class="status__stats--header">
        <div :class="statusClassName"></div>
        <p>Address</p>
    </div>
    <div class="status__stats--item">{{touchData.webSocketAddress}}</div>
    <div class="status__stats--header">FrameNumber</div>
    <div class="status__stats--item">{{touchData.frameNumber}}</div>
    <div class="status__stats--header">Touches</div>
    <div class="status__stats--item">{{touchCount}}</div>
  </div>
</template>

<script>
export default {
  name: "Status",
  inject: ["touchData"],
  computed: {
    touchCount() {
      return this.touchData?.points?.length ?? 0;
    },

    statusClassName() {
      return `status__indicator ${(this.touchData?.isConnected ?? false) ? 'connected' : 'disconnected'}`;
    }
  }
};
</script>
